---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/users":
    get:
      summary: Retrieves all users
      tags:
      - Users
      responses:
        '200':
          description: users found
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      "$ref": "#/components/schemas/User"
                required:
                - users
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: integer
      required:
      - id
      - name
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
